CUSTOMERS_FILE = data/publicChallenge.csv

PROBAS_TO_COMBINE = ../2014-01-16-rw/rwalks.probas ../2014-01-15-cust-all/rf.probas
PROBAS_PARAMS = -w 0.3 0.7
# PROBAS_PARAMS = -w 0.01 0.99
all: sol.csv
include ../../Makefile