# CUSTOMERS_FILE = interim/customers-100.txt
CUSTOMERS_FILE = interim/customers-0.02.txt
# CUSTOMERS_FILE = interim/customers-0.10.txt
# CUSTOMERS_FILE = data/publicChallenge.csv
rf_d: rf_direct.probas
include ../../Makefile