CUSTOMERS_FILE = data/publicChallenge.csv

PROBAS_TO_COMBINE = ../2014-01-16-rw/rwalks.probas
PROBAS_TO_COMBINE += ../2014-01-20-rf-allcustomers/rf_clf.probas
# PROBAS_TO_COMBINE += ../2014-01-19-newfeat-all/rf.probas
all: sol.csv
include ../../Makefile