# CUSTOMERS_FILE = interim/customers-100.txt
CUSTOMERS_FILE = interim/customers-0.02.txt
# CUSTOMERS_FILE = interim/customers-0.10.txt
# CUSTOMERS_FILE = data/publicChallenge.csv
PROBAS_TO_COMBINE = ../2014-01-23-rw-0.02/rwalks.probas
PROBAS_TO_COMBINE += ../2014-01-19-newfeat-0.02/rf.probas
all:sol.csv
include ../../Makefile